name: Build Kernel

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - master # Or your main branch

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev adb fastboot pigz python3-dev swig

    - name: Set up build environment
      run: |
        mkdir $GITHUB_WORKSPACE/kernel_build
        cd $GITHUB_WORKSPACE/kernel_build

        # dtc
        git clone https://github.com/ASUS-SM8475/platform_external_dtc.git
        cd platform_external_dtc/
        make
        export PATH="$GITHUB_WORKSPACE/kernel_build/platform_external_dtc:$PATH"
        cd ..

        # mkboot.img
        mkdir mkbootimg
        cd mkbootimg/
        wget https://android.googlesource.com/platform/system/tools/mkbootimg/+archive/d2bb0af5ba6d3198a3e99529c97eda1be0b5a093.tar.gz
        tar -xvzf d2bb0af5ba6d3198a3e99529c97eda1be0b5a093.tar.gz
        export PATH="$GITHUB_WORKSPACE/kernel_build/mkbootimg:$PATH"
        cd ..

        # clang
        wget https://mirrors.edge.kernel.org/pub/tools/llvm/files/llvm-19.1.6-x86_64.tar.gz
        tar -xvzf llvm-19.1.6-x86_64.tar.gz
        export PATH="$GITHUB_WORKSPACE/kernel_build/llvm-19.1.6-x86_64/bin:$PATH"

        # AIK for checking is kernel right?
        git clone https://github.com/Shubhamvis98/AIK.git

        #env
        export CC="clang"
        export CLANG_TRIPLE="aarch64-linux-gnu-"
        export CROSS_COMPILE="aarch64-linux-gnu-"
        export CROSS_COMPILE_ARM32="arm-linux-gnueabi-"
        export ARCH="arm64"

        # mkdtimg
        git clone https://github.com/affggh/mkdtimg.git
        cd mkdtimg
        make
        cd ..
        printenv
